### ISSUE TITLE
Standardization process transparency

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [webmachinelearning/charter#7]
As I find it a separate topic - this is a continuation to this post: https://github.com/webmachinelearning/webnn/issues/3#issuecomment-462452394

In response to:
> PS. And again, if someone doesn't want training functionality at all or in v1, please provide good reasons. Simple "No" isn't an argument into discussion.

@anssiko wrote:
> The group makes decisions based on consensus and participants do not need to provide reasons why they are not willing to expand the agreed upon scope.

> I mentioned that to clarify the process and mechanics for making charter changes (voting) differs from day-to-day decision-making (consensus-based). These aspects are explained in the charter document. You can reach out to me privately and I’m happy to answer any further procedural questions you may have to keep this issue focused on technical discussion.

Thank you for clarification, just hope you were driven with need of helping me (which I really appreciate then), but such a response comments are sensitive thing and otherwise I would find it highly inappropriate.

---

And as we are here already, I would like to rise this topic as well. While I understand a right to not to provide a reasons of decisions for things that would touch things like for example religion, ethnicity or sexual preferences, I completely disagree for the sake of transparency of this process for not providing reasons for (both including and not including) functionalities that are clearly strictly technical and not touching these sensitive areas.

**Comment by anssiko** [comment]
As the chair my job is to help group participants work productively together, make progress toward agreed upon goals, and help with process-related issues. My comments were just that, help and guidance relevant to all participants.

Since this group is not the right place to try change the generic and established W3C Community Group decision-making and voting procedures I have followed up with @DanielMazurkiewicz privately to continue this discussion with him.
